# Generated by Django 3.2.8 on 2023-02-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='user_name',
            field=models.CharField(default='user_', max_length=64),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
