# Generated by Django 3.2.8 on 2023-02-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230224_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
    ]
