# Generated by Django 3.2.8 on 2023-02-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_todouser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='birthday_year',
            field=models.PositiveIntegerField(default='Null'),
        ),
    ]
