# Generated by Django 4.1.7 on 2023-03-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230226_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
